# -*- coding: utf-8 -*-
"""hospital_er.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cv0oiqRdOXusiYBf6a_C8ge-bGibS6t3
"""

#mount and import hospital_er csv file
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/ER data/Copy of Hospital ER_Data.csv')

df.head()

#columns with numerical data
df.describe()

df['Patients CM'].value_counts()

# looking for missing values
df.isnull().sum()

#inspecting columns ["Department Referral"] and ["Patient Satisfaction Score"]
df.loc[:,["Department Referral","Patient Satisfaction Score"]]
# ["Patient Satisfaction Score"] 0 for score and representative of missing data, use for service improvement
# ["Department Referral"] not 0 but representative of no referral needed

df.head()

# concatenation Patient Full Name
df["Patient Full Name"] = df["Patient First Inital"] + " " + df["Patient Last Name"]
df.head()

df["Patient Gender"].value_counts()
# rename columns for clarity

df["Patient Gender"] = df["Patient Gender"].replace("M","Male")
df["Patient Gender"] = df["Patient Gender"].replace("F","Female")
df["Patient Gender"] = df["Patient Gender"].replace("NC","Not Conformed")
df["Patient Gender"].value_counts()

df.to_csv("cleaned_hospital_er.csv", index=False)